### ISSUE TITLE
Cannot Find Project Reference

### ISSUE THREAD

**Issue by Mayor-Meerkat** [ComputerElite/OculusGraphQLApiLib#1]
Hello, 

The error I am getting is "Unable to find project'..\ComputerUtils\ComputerUtils\ComputerUtils.csproj'. Check that the project reference is valid and that the project file exists."

In the solution explorer is shows the file as missing. I cloned the repo directly. I already tried deleting everything and recloning.

My goal in the end is just to be able to pull a full list of games the Oculus Store has to offer. Release dates, publishers and all those types of properties would be amazing too.

Thank you!

**Comment by ComputerElite** [comment]
Hi,
For that specific purpose you can just use the OculusDB api: https://oculusdb.rui2015.me/api/v1/allapps
Docs: https://oculusdb.rui2015.me/api/docs

If you want to use the library you need to also include the ComputerUtils project from this repo: https://github.com/ComputerElite/ComputerUtils

**Comment by Mayor-Meerkat** [comment]
Hi, 

That api is exactly what I am looking for - Thank you so much! Is there anyway I could see what the GraphQL query looks like for the allapps end point? That would be even better.

Thank you again!

**Comment by ComputerElite** [comment]
https://github.com/ComputerElite/OculusGraphQLApiLib/blob/main/OculusGraphQLApiLib/GraphQL/GraphQLClient.cs#L126

**Comment by Mayor-Meerkat** [comment]
Thank you again!
